// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzBhDR5HOL_Q9zmlhmD9kaXlGdTKPSJ3Y',
    appId: '1:382968144766:web:35347c0442236cfaf0492f',
    messagingSenderId: '382968144766',
    projectId: 'practice-f8667',
    authDomain: 'practice-f8667.firebaseapp.com',
    storageBucket: 'practice-f8667.appspot.com',
    measurementId: 'G-YT66WZBK0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrTMkg_lg9jWVzELE70-uX5NECXdVnyAo',
    appId: '1:382968144766:android:5080596312096247f0492f',
    messagingSenderId: '382968144766',
    projectId: 'practice-f8667',
    storageBucket: 'practice-f8667.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDupHoONNMPbLeod3rJrxvZ4qbnYXfemdo',
    appId: '1:382968144766:ios:6befb4d8b175f897f0492f',
    messagingSenderId: '382968144766',
    projectId: 'practice-f8667',
    storageBucket: 'practice-f8667.appspot.com',
    iosBundleId: 'com.example.todoey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDupHoONNMPbLeod3rJrxvZ4qbnYXfemdo',
    appId: '1:382968144766:ios:6befb4d8b175f897f0492f',
    messagingSenderId: '382968144766',
    projectId: 'practice-f8667',
    storageBucket: 'practice-f8667.appspot.com',
    iosBundleId: 'com.example.todoey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzBhDR5HOL_Q9zmlhmD9kaXlGdTKPSJ3Y',
    appId: '1:382968144766:web:b88abacc12ca722ef0492f',
    messagingSenderId: '382968144766',
    projectId: 'practice-f8667',
    authDomain: 'practice-f8667.firebaseapp.com',
    storageBucket: 'practice-f8667.appspot.com',
    measurementId: 'G-QL7T1B9XEY',
  );
}
